name: ruby
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *' # every hour
jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: bin/add-ruby.rb
      - run: "bin/git-push.sh 'GitHub Actions: Add ruby'"
