name: ruby
on:
  push:
    branches: [master]
  schedule:
    # ruby-docker-images uses `cron: "0 17 * * *"`
    # https://github.com/ruby/ruby-docker-images/blob/master/.circleci/config.yml
    - cron: '0,5,10,15,20,30,40,50 17 * * *'
  workflow_dispatch:
jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: bin/add-ruby.rb
      - run: "bin/git-push.sh 'GitHub Actions: Add ruby'"
