name: optcarrot
on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: "00 15 * * *"
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          # bundler-cache: true
      - run: ruby benchmark/optcarrot.rb
